### ISSUE TITLE
Gooey v1.0.5 dependency wxpython==4.1.0 is not available on conda-forge

### ISSUE THREAD

**Issue by jfcorbett** [conda-forge/gooey-feedstock#6]
Unable to complete PR #5 (gooey v1.0.5) because dependency `wxpython ==4.1.0` is not yet available on conda-forge for Windows and MacOS, as per this issue reported in the wxpython feedstock: https://github.com/conda-forge/wxpython-feedstock/issues/52

**Comment by casperdcl** [comment]
fixed by #14
